- name: Add mesos repo apt key
  apt_key:
    id: E56151BF
    keyserver: keyserver.ubuntu.com

- name: Add mesos repo
  lineinfile: dest=/etc/apt/sources.list state=present line='{{item}}'
  with_items:
    - "deb https://mirrors.ustc.edu.cn/debian jessie-backports main"
    - "deb http://repos.mesosphere.io/debian jessie main"
  register: mesos_repo

- name: Update packages
  apt:
    update_cache: yes
  when: mesos_repo.changed

- name: Install mesos packages
  apt: name={{ item }} state=present
  with_items:
    - mesos
    - libssl1.0.0
  environment:
    # do not start at the end of install
    RUNLEVEL: 1

- name: Ensure mesos-slave directory
  file:
    path: "{{item}}"
    state: directory
    recurse: yes
  with_items:
    - /var/lib/mesos/slave

- name: Write mesos-slave systemd unit file
  template: src=mesos-slave.service.j2 dest=/etc/systemd/system/mesos-slave.service
  register: mesos_slave_service
  notify:
    - restart mesos-slave

- name: Reload systemd
  systemd: daemon_reload=yes
  when: mesos_slave_service.changed

- name: Start mesos-slave service
  service: name=mesos-slave state=started enabled=yes

# overwrite origin enable service
- name: Reenable mesos-slave service
  command: systemctl reenable mesos-slave.service

- name: Disable mesos-master services
  service: name=mesos-master enabled=no
  when: ansible_host not in groups['mesos-master']
